---
abstract: 'Tool to sort DWG files by version.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.59
  File::Object: 0
  File::Spec::Functions: 0
  Test::More: 0
  Test::NoWarnings: 0
  Test::Output: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-DWG-Sort
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  CAD::AutoCAD::Detect: 0.02
  Class::Utils: 0
  Error::Pure: 0
  File::Copy: 0
  File::Find::Rule: 0
  File::Find::Rule::DWG: 0
  File::Path: 0
  File::Spec::Functions: 0
  Getopt::Std: 0
  perl: 5.6.0
resources:
  bugtracker: https://github.com/michal-josef-spacek/App-DWG-Sort/issues
  homepage: https://github.com/michal-josef-spacek/App-DWG-Sort
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/App-DWG-Sort
version: '0.02'
